"""Add phone number

Revision ID: 72302725cfa7
Revises: da73dc04c273
Create Date: 2023-07-12 19:45:01.898707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72302725cfa7'
down_revision = 'da73dc04c273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_no')
    # ### end Alembic commands ###
