"""Auto - votes

Revision ID: da73dc04c273
Revises: a8b735bb4167
Create Date: 2023-07-12 19:36:32.582255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da73dc04c273"
down_revision = "a8b735bb4167"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.add_column(
        "posts", sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.alter_column(
        "posts",
        "published",
        existing_type=sa.BOOLEAN(),
        existing_server_default=sa.text("true"),
    )
    op.drop_constraint("posts_users_fk", "posts", type_="foreignkey")
    op.create_foreign_key(
        None,
        "posts",
        "users",
        ["owner_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_users_fk", "posts", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "posts",
        "published",
        existing_type=sa.BOOLEAN(),
        existing_server_default=sa.text("true"),
    )
    op.drop_column("posts", "updated_at")
    op.drop_table("votes")
    # ### end Alembic commands ###
